---
title: "Curriculum Vitae 2018"
author: "Samuel Dale McQuillin, Ph.D."
email: MCQUILLS@mailbox.sc.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
jobtitle: Assistant Professor, University of South Carolina
keywords: mentoring, motivational interviewing
linkcolor: blue
fontawesome: yes
phone: 803-777-6725
address: 1512 Pendleton St., Office 462, Barnwell College, Columbia, SC, 29208
updated: yes
urlcolor: blue
web: goo.gl/41tAyJ
---

# Employment

*University of South Carolina*
Assistant Professor (Columbia) \hfill 2016-Present  
Department of Psychology

*University of Houston*
Assistant Professor (Houston)  \hfill 2012-2016  
Department of Psychological Health and Learning Sciences  

# Education

*University of South Carolina*, Ph.D. Psychology \hfill 2012

*Cypress Fairbanks ISD*, Pre-Doctoral APA Accredited Internship \hfill 2011

*University of South Carolina*, M.A. Psychology \hfill 2010

*University of South Carolina*, B.A. Experimental Psychology \hfill 2007

#Professional Affiliation  

Research Board Member, National Mentoring Resource Center \hfill 2015-present    
Editorial Board, Journal of Community Psychology \hfill 2017-present  
Contributing Editor, Chronicle of Evidence Based Mentoring \hfill 2018-present  
Board Member, Richland County Public Education Partners \hfill 2018-present  
Accredited Teen Triple P (Positive Parenting Program) Primary Care Provider \hfill 2010-present  
Core Beta Tester, OpenMx Structural Equation Modeling Software \hfill 2009  
Member, Association for Behavioral and Cognitive Therapies \hfill 2007-present  
Member, American Psychological Association \hfill 2013-present  
National Association of School Psychologist \hfill 2007-present  

#Grant Awards/Activity

Co-Principal Investigator \hfill 2017-2018  
Boys Hope Girls Hope Academy:  
Program Practices and Positive Youth Development  
The Stupski Foundation, $300,000  

Co-Investigator (PI: Scott Decker, University of South Carolina) \hfill 2017-2020  
South Carolina Learning Disabilities Research Project  
Office of Special Education Services, SC, $738,318

Investigator (PI: Jane Roberts, University of South Carolina) \hfill 2017-2021  
Emergence and Stability of Autism in Fragile X Syndrome: longitudinal extension  
R01 MH90194-06  
National Institute of Mental Health, $3,550,989  

Principal Investigator \hfill 2016-2018   
Brief Instrumental School-Based Mentoring to Reduce Adolescent Disruptive Behavior  
Society for the Study of School Psychology Early Career Award, $19,723  

Principal Investigator \hfill 2015-2016  
Promoting Adolescent Mental health through School-Based Mentoring  
Hogg Foundation, $19,196  

Principal Investigator \hfill 2015-2016  
Training Paraprofessionals to Use Motivational Interviewing  
New Faculty Research Program, University of Houston, $6,000  

Investigator (PI: Anne McClellan, University of Houston) \hfill 2014-2016  
Motivational Coaching Instruction for School Administrators  
Provost's Teaching Innovation Proposal, $25,000  

Investigator (PI: Jacqueline Hawkins, University of Houston) \hfill 2014-2015  
A+ Program Evaluation Research Design Proposal  
A+ Challenge Network, $57,000  

Investigator (PI: Norma Olvera, University of Houston) \hfill 2013-2014  
Hispanic Health Coalition, Healthy Lifestyle Programs  
Harris County Hospital District Foundation, $36,000  

Statistical Consultant (PI: Jane Roberts, University of South Carolina) \hfill 2011-2016  
1R01MH090194-01A1  
Emergence and Stability of Autism in Fragile X Syndrome  
National Institute of Mental Health, $1,790,000  

Methodological Consultant (PI: Bradley Smith, University of South Carolina) \hfill 2010-2011  
Applications of Triple P Parenting Program in the Promotion of Health and Wellness  
University of South Carolina, $20,000  

Principal Investigator \hfill 2009-2010  
United Health Heroes, Youth Serve America  
Supplement for grant funded by the Office of Minority Health, $1,000  

Program Evaluator (PI: Bradley Smith) \hfill 2007-2009  
Marlboro County Youth Empowerment Program  
Office of Minority Health, $248,000. 



# Publications

## Peer Reviewed Journal Articles[^1]


[^1]: Indicates author or presenter was student/mentee of Dr. McQuillin.

1. McQuillin, S., Lyons, M., Becker, K., Hart^1^, M., Cohen^1^, K. (accepted pending revisions) Strengthening and expanding child services in low resource communities: The role of task-shifting and just-in-time training. American Journal of Community Psychology. 
1. Lyons, M., McQuillin, S., Henderson, L. (in press) Finding the sweet spot: Investigating the effects of relationship closeness and instrumental activities in school-based mentoring. American Journal of Community Psychology.
1. McQuillin, S., Lyons, M., Clayton^1^, B., Anderson^1^, J. (2018) Assessing the impact of school-based mentoring: Common problems and solutions associated with evaluating non-prescriptive youth development programs. Applied Developmental Science. http://doi.org/10.1080/10888691.2018.1454837
1. Lyons, M., McQuillin, S. (2018) A reanalysis of the Student Mentoring Program: Estimating treatment effects by the quality of the mentoring relationship. School Psychology Quarterly. https://doi.org/10.1037/spq0000265
1. Payan, A., Keller-Margulis, M., Burridge, A., McQuillin, S., Hassett, K. (2018) Assessing teacher usability of written expression curriculum-based measurement. Assessment for Effective Intervention, 1-14.  https://doi.org/10.1177/1534508418781007
1. Strait, G., Smith, B., McQuillin, S. (2018) The Test-Retest Reliability, Predictive Validity, and Cut Score Precision and Efficiency of Aggregated Randomly Generated Math Curriculum-Based Measurements. Assessment for Effective Intervention.
1. Nowell^1^, K., Kochel, R. P., McQuillin, S., Mire, S. (2017). Intellectual functioning and autism spectrum disorder: Can profiles inform identification of subpopulations? Journal of Autism and Developmental Disorders. DOI: http://dx.doi.org/10.1007/s40489-017-0118-0
1. Strait, G., Lee, E., McQuillin, S., Terry, J., Cebada, M., Strait, E. (2017). The student check-up: effects of paraprofessional-delivered motivational interviewing on academic outcomes. *Advances in School Mental Health Promotion*.  http://dx.doi.org/10.1080/1754730X.2017.1333915
1. Keller-Margulis, M., McQuillin, S., Ochs^1^, S., Castaneda, J., Jones, J. (2017). Identifying students at-risk: An examination of computer-adaptive measures and latent class growth analysis. *Journal of Applied School Psychology*.
1. Gregus, S., Rodriguez, J., Pastrana, F., Craig, J., McQuillin, S., Cavell, T. (2017).Teacher self-efficacy and intentions to use anti-bullying practices as predictors of children's peer victimization. *School Psychology Review*.
1. Lyons, M., Jones, S., Smith, B., McQuillin, S., Reid, E., Jacobs^1^, G., McClellan, A. (2017). Motivation coaching training for instructional coaches: A pilot study of motivational interviewing skills training. *Mentoring and Tutoring: Partnership in Learning*.
1. McQuillin, S., Lyons, M (2016). Brief instrumental school-based mentoring for middle school students: theory and impact. *Advances in School Mental Health Promotion, 9(2), 73-89.*
1. Ochs^1^, S., Keller-Margulis, M., McQuillin, S., Jones, J. (2016). The validity and diagnostic accuracy of a computer adaptive test of reading. *Research And Practice in the Schools, 4(1), 29-41.*
1. Dempsey, J., McQuillin, S., Butler, A. M., & Axelrad, M. E. (2016). Maternal Depression and Parent Management Training Outcomes. *Journal of Clinical Psychology in Medical Settings*, 1-7. http://doi.org/10.1007/s10880-016-9461-z
1. Robinson, A., Roberts, J., Brady, N., McQuillin, S., Warren, S. (2016). Physiological Correlates of Maternal Responsivity in Mothers of Preschoolers with Fragile X Syndrome. *American Journal on Intellectual and Developmental Disabilities. 121(2), 111-120.*
1. McQuillin, S., Strait, G., Saeki, E. (2015). Program support and value of training in mentor satisfaction and anticipated continuation of school-based mentoring relationships. *Mentoring and Tutoring: Partnership in Learning, 23(2), 133-148.*
1. Terry, J., Smith, A., Warren, P., Miller, M., McQuillin, S., Wolfer, T., & Weist, M. (2015). Incorporation of evidence-based practices into faith-based organization service programs. *Journal of Psychology and Theology, 43, 212-223.*
1. McQuillin, S., Smith, B., & Strait, G., Ingram^1^, A., (2015). Brief Instrumental School- Based Mentoring for First and Second Year Middle School Students: A Randomized Evaluation. *Journal of Community Psychology 43(7), 885-889.*
1. Strait, G., McQuillin, S., Terry, J., Smith, B. (2014). School-based motivational interviewing with students, teachers, and parents: new developments and future direction. *Advances in School Mental Health Promotion, 7(4), 2014, 205-207.*
1. Terry, J. D., Smith, B. H., & McQuillin, S. D. (2014). Teaching evidence-based practice in service-learning: A model for education and service. *Journal on Excellence in College Teaching, 25(1), 55-69.*
1. Roberts, J., Tonnsen, B., Robinson, M., McQuillin, S., Hatton, D. (2014) Temperament factor structure in fragile x syndrome: The children's behavior questionnaire. *Research in Developmental Disabilities, 35, 563-571.*
1. Terry, J., Strait, G., McQuillin, S., Smith, B. (2014). Dosage effects of motivational interviewing onmiddle-school students' academic performance: Randomized evaluation of one versus two sessions. *Advances in School Mental Health Promotion, 7(1), 62-74.*
1. McQuillin, S., Terry, J., Strait, S., Smith, B. (2013). Innovation in school-based mentoring: matching the context, structure, and goals of mentoring with evidence-based practices. *Advances in School Mental Health Promotion, 6(4), 280-294.*
1. Terry, J., Strait, G., Smith, B., McQuillin, S., ( 2013). Motivational Interviewing to Improve Middle School Students' Academic performance: a replication study. *Journal of Community Psychology.*
1. Strait, G., Smith, B., McQuillin, S., Terry, J., Swan, S., Malone, P. (2012). Randomized trial of motivational interviewing to improve students' academic performance. *Journal of Community Psychology, 40(8), 1032-1039.*
1. Strait, G. McQuillin, S., Smith, B., Englund, J. (2012). Using motivational interviewing with children and adolescents: a cognitive and neuro developmental perspective. *Advances in School Mental Health Promotion, 5(4), 1-15.*
1. Kelly, R., Hills, K., Huebner, S., McQuillin, S. (2012). The longitudinal stability and dynamics of group membership in the dual-factor model of mental health: psychosocial predictors of mental health. *Canadian Journal of School Psychology, 27(4), 337-355.*
1. McQuillin, S., Smith, B., & Strait, G. (2011). Randomized evaluation of a single semester transitional mentoringprogram for first year middle school students: A cautionary result for brief school-based mentoring programs. *Journal of Community Psychology, 39(7), 844-859.*
1. Warren, P., Richardson, D., & McQuillin, S. (2011). Distinguishing forms of nondirect aggression. *Aggressive Behavior, 37, 291-301.*
1. Smith, B., Gahagan, J., McQuillin, S., Haywood, B., Cole, P., Bolton, C., & Wampler, M.(2011). The development of a service-learning program for first-year students based on the hallmarks of high quality service-learning and rigorous program evaluation. *Innovative Higher Education, 36,1-17.*
1. Fairchild, A., & McQuillin S., (2010). Evaluating mediation and moderation effects in school psychology: Apresentation of methods and review of current practice. *Journal of School Psychology,45, 54-84.*

## Other Publications  

* McQuillin, S. (2018, August 22) Improving Mentoring by Improving Mentor Training [Blog Post]. National Mentoring Resource Center. Retrieved from https://nationalmentoringresourcecenter.org/index.php/nmrc-blog/372-improving-mentoring-by-improving-mentor-training.html  
* Strait, G., McQuillin, Anderson^1^, J., & Williams, C. (2018). Practical applications of student focused motivational interviewing. In McNamara, E. (eds.), Motivational Interviewing Theory Practice, and Applications with Children and Young People. Positive Behaviour Management.  
* Garringer, M., McQuillin, S., McDaniel^1^ H. (2017) Examining Youth Mentoring Services Across America: Findings from the 2016 National Mentoring Program Survey. Technical Report produced by MENTOR: The National Mentoring Partnership. http://www.mentoring.org/program-resources/mentor-resources-and-publications/national-survey/  
* McQuillin, S., Smith, B., McLelland^1^, B. (2014) Using practice-based evidence to inform the development of school-based mentoring. *The Community Psychologist, 47, 2, 31-32.*  
* Strait, G., Terry, J., McQuillin, S., Smith, B. (2013). Motivational interviewing: ready for adults and emergent for adolescents. *The Community Psychologist, 46(1), 26-28.*  
* Smith, B., McQuillin, S., & Shapiro, C. (2008). An installation adaptation diffusion model of university-community-school partnerships. *The Community Psychologist, 42(1),43-46.*  

#Peer Reviewed Presentations

1. McQuillin, S., Lyons, M. (2017) Treatment construct validity in school-based mentoring intervention research. Paper presented at the annual meeting for the Society for Research on Educational Effectiveness, Washington, DC. 
1. McQuillin, S., McDaniel^1^, H. (2017) Using Motivational Interviewing in School-Based Mentoring Programs. Paper presented at the annual meeting for the Society for Prevention Research, Washington, DC.
1. Lyons, M., McQuillin, S., Lamont, A. (2017) A Reanalysis of the Student Mentoring Program: Estimating Treatment Effects by the Quality of the Mentoring Relationship.
1. McQuillin, S. (2017) Changing the way we train mentors: Just in Time Training & Motivational Interviewing. Paper presented at the annual National Mentoring Summit in Washington, DC.
1. McQuillin, S., Jacobs^1^, G., Sajovek^1^, P., Johnson^1^, B., Anderson^1^, A. (2016). Brief Instrumental School-Based Mentoring for Adolescents-Theory, Practice, and Impact Evaluations. Symposium presented at the annual meeting for the American Psychological Association, Denver, CO.
1. McQuillin, S. (2015). From harmful to helpful: transforming youth mentoring through task shifting, evidence- based practice, and practice-based evidence. Symposium presented at the annual meeting for the Association of Psychological Science, New York, NY.
1. McQuillin, S. (2014). The University of Houston Academic Mentoring Program for Education and Development (AMPED). Paper presented at the annual meeting of the American Psychological Association, Washington, DC.
1. McQuillin, S., Smith, B., McLelland^1^, B. (2014). Motivaitonal Interviewing and School-Based Mentoring: Process, Procedures, Implementation, and Results. Paper presented at the annual meeting of the American Psychological Association, Washington, DC.
1. McQuillin, S. (2014). School-based instrumental mentoring for middle-school students: past, present future. Poster presented at the annual meeting of the Society for Prevention Research, Washington, DC.
1. McQuillin, S., Saeki, E. (2013). Mechanisms of Change in School-Based Psychosocial Interventions. Paper presented at the annual meeting of the National Association of School Psychologists, Seattle, WA.
1. McQuillin, S., Cavell, T., Elledge, E., Strait, G., Smith, B., Terry, J. (2012). Brief manualized school-based mentoring interventions for secondary students: Results and suggestions from two randomized trials. In McQuillin, S. (Chair), Principles of change in school-based mentoring and coaching interventions. New findingsand implications from five randomized controlled studies. Presented at the symposium conducted at the 46th annual convention of the Association for Behavioral and Cognitive Therapies, National Harbor, MD.
1. Smith, B., Sanders, M., McQuillin, S., Fairchild, A., & Anello, V. (2010). Investing in the future of psychotherapy research: Statistical best practices and seven methodological considerations for studying mechanisms of action. Symposium presented at the annual meeting of the Association for Cognitive and Behavioral Therapies, San Francisco, CA.
1. McQuillin, S. (2010). Randomized evaluation of a school based mentoring program for transitioning middle school students: An efficacy trial. Poster presented at the annual meeting of the Association for Cognitive and Behavioral Therapies, San Francisco, CA.
1. McQuillin, S. & Annelo, V. (2010). Applications of the public health model to school based mental health collaboration in school-university-community partnerships. Paper presented at the annual meeting of the National Association of School Psychologists in Chicago, IL.
1. McQuillin, S. (2010). Statistical mediation and moderation in program design and evaluation. Paper presented at the annual meeting of the National Association of School Psychologists in Chicago, IL.
1. Strait, G., Cole, C., McQuillin, S. (2009, February). Psychometric properties of brief basic math skill assessments.Paper presented at the annual meeting of the National Association of School Psychologist in Boston, MA.
1. Pender, C.A.S., Strait, G., McQuillin, S., Carl, W. (2008, February). Efficacy and psychometrics of a middle-school remedial math curriculum. Oral presentation presented at the annual meeting of the National Association of School Psychologists in New Orleans, LA.
1. Pender, C.A.S., Smith, B., Strait, G., McQuillin, S., Ardoin, S., (2007, November). Math intervention delivered by paraprofessionals to high-risk middle-school students in the challenging horizons program. Poster presented at the annual meeting of the Association for Behavioral and Cognitive Therapies in Philadelphia, PA.
1. Pender, C.A.S., Strait, G., & McQuillin, S. (2007, March). Improving middle school students' math word problem solving skills. Poster presented at the annual meeting of the National Association of School Psychologists in New York, NY.
1. McQuillin, S., & Terry, J. (2007, April). The challenging horizons program: Contributions of USC undergraduates to the development of an evidence-based, award winning program. Paper presented at the annual Discovery Day of the University of South Carolina, Columbia, SC.
1. McQuillin, S., Thompson, S. & Strait, G., Smith, B. & Pender, C. (2006, April). Curriculum based measurement and state-of-the-art training to help middle school students solve math word problems. Paper presented at the annual Discovery Day of the University of South Carolina, Columbia, SC.
1. Strait, G., McQuillin, S., Thompson, S. Smith, B. & Pender, C.(2006, April). State-of-the-Art Individually Paced Intervention to Improve Math Word Problem Solving. Poster presented at the annual Discover Day of the University of South Carolina, Columbia, SC.

##Invited talks and Workshops

Garringer, M., McQuillin, S. (2017) Key Findings and Conclusions from the 2016 National Mentoring Program Survey. Webinar produced by MENTOR: The National Mentoring Project.  

McQuillin, S., Duncombe, S., Siegfried, A. (2017) A Fresh Look at Logic Models: Enhance and Amply Their Value. Webinar presented on behalf of the Collaborative Mentoring Webinar Series, produced by MENTOR: The National Mentoring Partnership.  

Deustch, N., McQuillin, S. (2016). Getting Results for Our Youth: Evaluating Programs for Continuous Improvement. Webinar presented on behalf of the My Brothers Keeper Alliance Webinar Series, via MENTOR, the National Mentoring Partnership.

Garringer, M., McQuillin, S. (2016). Introduction to Program Evaluation for Youth Mentoring Programs. Workshop presented at MENTOR-Con. Pittsburgh, PA.

McQuillin, S. (2015). Helping kids change. Workshop presented at the Positive Change Conference, Compass Mark, Lancaster, PA. 

McQuillin, S. (2015). Improving the impact of school-based mentoring. Keynote speaker, Texas Mentoring Summit, San Antonio, TX.

McQuillin, S. (2014). Using motivational interviewing in the context of teacher coaching. Three day workshop presented to Houston area master coaches. Teach2Lead Houston, Houston, TX.

McQuillin, S., McLelland^1^, B.(2013). Motivational Interviewing in Schools. Workshop provided to pre-doctoral interns as part of their APA Accredited Internship in Psychology. Cypress, TX

McQuillin, S., McLelland^1^, B.(2012). Motivating students to succeed in school. Workshop provided to student support counselors at YES Prep Charter School, Houston, TX.

McQuillin, S., McLelland^1^, B.(2012). Mentoring and Motivational Interviewing. Workshop provided to pre-doctoral interns as part of their APA Accredited Internship in Psychology. Cypress, TX

#Awards

3rd Place in Social Psychological Sciences, Discovery Day, University of South Carolina \hfill 2006

Megellan Voyager Research Award \hfill 2007

2nd Place in Social Psychological Sciences, Discovery Day, University of South Carolina \hfill 2007

Inducted into Phi Beta Kappa National Honor Society \hfill 2007

USC Graduate Student Travel Grants, totaling $1,700 \hfill 2010

American Psychological Association Achievement Award for Early Career Professionals \hfill 2014

University of Houston Certificate of Excellence on Behalf of Provost Short \hfill 2015

Award for Research Excellence, University of Houston \hfill 2015

Society for the Study of School Psychology Early Career Award \hfill 2016

#Teaching

##Graduate

Evidence-Based Interventions in Psychology, University of Houston

History and Philosophy of Psychological Systems, University of Houston

Research Methods in School Psychology, University of Houston

Ecological Behavioral Interventions, University of Houston

Behavioral Consultation, University of Houston

Systems Applications in Psychological Services, University of South Carolina

Assessment of Emotional and Behavioral Functioning, University of South Carolina

Psychological Consultation and Systems Interventions, University of South Carolina

Lab Instructor: Quantiative Methods for Behavioral Data I, University of South Carolina

Lab Instructor: Quantiatative Methods for Behavioral Data II, University of South Carolina

##Undergraduate 

Research Methods in Psychology, University of South Carolina

Research Methods in Human Development, University of Houston

Children & Exceptionality, University of South Carolina

# Service on Student Dissertations and Theses  

Susceptibility to Peer Influence and Social Anxiety: An Exploratory Study \hfill 2012  
Chair of candidacy project for Ph.D. Student Brent Smith.  

ABA Therapy in the ASD Population: Long Term Social Functioning and Gender Differences \hfill 2013  
Chair of candidacy project for Ph.D. Student Allyson Tagliarina.  

Parent Stress Response Relative to Boys and Girls Born Preterm \hfill 2014  
Chair of candidacy project for Ph.D. Student Sonia Babu.  

Parent Knowledge of Sexual Trauma of Sexually Abused Foster Children \hfill	2014  
Chair of Dissertation project for Ph.D. Student Brent Smith.  

Psychometric Properties of the Alabama Parenting Questionnaire-Preschool Revision \hfill	2014  
Chair of dissertation project for Ph.D. Student Erika Gonzalez.  

Comparing Parent Behaviors of Mothers and Fathers of Children with ASD	\hfill 2014  
Methodologist of candidacy project for Ph.D. Student Rachel H. Fein.  

Validation of the Causes of Peer Rejection Scale	\hfill 2015  
Chair of dissertation project for Ph.D. Student Aaron Boyce.  

Relations between Intellectual Profiles, Core Symptoms, and Age in Youth with Autism \hfill 2015   
Chair of dissertation project for Ph.D. Student Kerri Nowell.  

Motivational Interviewing: Perceptions of Empathy and Reactance	\hfill 2015  
Chair of candidacy project for Ph.D. Student Brittany McLelland.   

Parenting Stress as a Predictor of Child Externalizing Behaviors	\hfill 2015  
Chair of dissertation project for Ph.D. Student Erika Gonzalez. 

An Analysis of National Trends in Composition of Psychologists in the United States	\hfill 2015   
Methodologist of dissertation project for Ph.D. Student Eliza Alexander.  

Predictors of Parent Behaviors During Play Interactions with Children with ASD	\hfill 2015  
Methodologist of dissertation project for Ph.D. Student Rachel H. Fein.   

#Service on University and Department Committees  

Social Committee, UH	\hfill 2012  
Secretary: Technology Committee, UH	\hfill 2013  
Search Committee Member: Program Director School Psychology, UH 	\hfill 2012  
Search Committee Member: School Psychology Assistant Professor, UH	\hfill 2013  
Search Committee Member: Assistant Professor EPSY, UH	\hfill 2014  
Search Committee Member: Quantitative Methods, UH	\hfill 2015  
Faculty Executive Committee Member, Department of Psychology, USC	\hfill 2017-2020  
Faculty Welfare Committee Member, University Senate Committee, USC	\hfill 2017-2020  


#Clinical/Field/Industry Experience

Program Director, AMPED, Columbia, SC, & 5th Ward, Houston TX	\hfill 2011-current  
Description: Developed, directed and coordinated school-based mentoring program for children who display disruptive behavior in local area middle schools. Approximately 650 youth have participated in this program and related studies. 

Independent Consultant	\hfill 2012-current  
Description: Provided private organizational consultation and collaboration to hundreds of administrators and counselors in nationally top-ranked charter schools including YES Prep and KIPP public schools, and two of the largest public school districts in the US (Houston Independent School District and Cypress Fairbanks Independent School District). Services involved integrating evidence-based practices-including Motivational Interviewing, School-Based Mentoring, and behavior modification-in routine educational settings.

Independent Consultant: MENTOR: National Mentoring Partnership	\hfill 2016-2017  
Description: Aided in the development, deployment, analysis, and reporting of a nationally representative sample of mentoring programs. 

Psychologist Intern, Cypress Fairbanks ISD, Cypress, TX	\hfill 2011-2012  
Supervisor: Shawn Hirsch, Ph.D., LP, LSSP  
Description: Provided manualized evidence-based counseling services for students with emotional or behavioral disorders, psychological assessment of students suspected of emotional and/or behavioral disorders, parent management training, and assessment/consultation for children with autism spectrum disorders.  

Motivational Interviewing Counselor, Columbia, SC	\hfill 2010-2011  
Supervisor: Bradley H. Smith, Ph.D.  
Description: Provided counseling services to 24 middle school students over the course of 5 months in the context of a randomized controlled trial of brief school-based motivational interviewing.  

Family Therapy Facilitator and Co-Counselor , Columbia SC	\hfill 2009-2010  
Supervisors: Kimberly Hills, Ph.D., LP, LSSP, Ashley Brewer, Ph.D., LP, LSSP  
Description: Facilitated a manualized family intervention program designed to help students recover from expulsion in the public school system.  Group family sessions involved guided discussions on family communication, family values, discipline, peer pressure, gang activity.  

School Psychology Practicum Student, Columbia SC	\hfill 2009-2010  
Supervisors: Kimberly Hills, Ph.D., LP, LSSP  
Description: Coordinated the implementation of a manualized tier two behavioral support program for children ith emotional and behavioral disorders. Provided psychological services including behavioral consultation, counseling, and crisis intervention. Provided psychological assessment services including academic, cognitive, curriculum-based assessments; assessment of children with autism spectrum disorders; and functional behavioral assessment.  

School Psychology Practicum Student, Lexington, SC	\hfill 2008-2009  
Supervisors: Mark Posey, Ph.D., LP, LSSP  
Description: Provided supervised psychological services including cognitive, academic, and behavioral assessment, cognitive behavioral therapy, academic intervention, behavior modification, and consultation in the middle and high school context.  

Site Supervisors & Program Evaluator, Marlboro County, SC	\hfill 2007-2009  
Supervisors: Bradhley H. Smith, Ph.D.
Description: Provided direct and supervisory services in a youth empowerment intervention for minority youth at risk of emotional, behavioral, and health problems. Responsibilities included training the paraprofessional staff of the program and providing direct services including behavior modification, counseling, and health instruction. Later assumed role of program evaluator and intervention coordinator.  

Lead Interventionist, Challenging Horizons Program (CHP), Columbia, SC	\hfill 2006-2008  
Supervisors: Carolyn A.S. Pender, Ph.D., LP  
Description: Served as Counselor and interventionist in an intensive six-week evidence-based summer treatment program for middle and high school students with severe behavioral, emotional, social, and academic difficulties, including Biopolar Disorder, Attention-Deficit/Hyperactivity Disorder, Learning Disabilities, and thought disorder.

