---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "Curriculum Vitae 2018"
author: Samuel Dale McQuillin, Ph.D.

jobtitle: "Assistant Professor, University of South Carolina"
address: "1512 Pendleton St., Office 462, Barnwell College, Columbia, SC, 29208"
fontawesome: yes
email: MCQUILLS@mailbox.sc.edu
phone: "803-777-6725"
web: goo.gl/41tAyJ
updated: yes

keywords: mentoring, motivational interviewing 

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Employment

*University of South Carolina*

Assistant Professor (Columbia) \hfill 2016-Present

*University of Houston*

Assistant Professor (Houston) \hfill 2012-2016

# Education

*University of South Carolina*, Ph.D. Psychology \hfill 2012

*Cypress Fairbanks ISD*, Pre-Doctoral APA Accredited Internship \hfill 2011

*University of South Carolina*, M.A. Psychology \hfill 2010

*University of South Carolina*, B.A. Experimental Psychology \hfill 2007


# Publications

## Journal Articles

1. Strait, G., Lee, E., McQuillin, S., Terry, J., Cebada, M., Strait, E. (2017). The student check-up: effects of paraprofessional-delivered motivational interviewing on academic outcomes. *Advances in School Mental Health Promotion*. http://dx.doi.org/10.1080/1754730X.2017.1333915

1. Keller-Margulis, M., McQuillin, S., Ochs, S., Castaneda, J., Jones, J. (in press). Identifying students at-risk: An examination of computer-adaptive measures and latent class growth analysis. *Journal of Applied School Psychology*.

1. Gregus, S., Rodriguez, J., Pastrana, F., Craig, J., McQuillin, S., Cavell, T. (in press).Teacher self-efficacy and intentions to use anti-bullying practices as predictors of children's peer victimization. *School Psychology Review*.

1. Lyons, M., Jones, S., Smith, B., McQuillin, S., Reid, E., Jacobs, G., McClellan, A. (in press). Motivation coaching training for instructional coaches: A pilot study of motivational interviewing skills training. *Mentoring and Tutoring: Partnership in Learning*.

1. McQuillin, S., Lyons, M (2016). Brief instrumental school-based mentoring for middle school students: theory and impact. *Advances in School Mental Health Promotion, 9(2), 73-89.*

1. Ochs, S., Keller-Margulis, M., McQuillin, S., Jones, J. (2016). The validity and diagnostic accuracy of a computer adaptive test of reading. *Research And Practice in the Schools, 4(1), 29-41.*

1. Dempsey, J., McQuillin, S., Butler, A. M., & Axelrad, M. E. (2016). Maternal Depression and Parent Management Training Outcomes. *Journal of Clinical Psychology in Medical Settings*, 1-7. http://doi.org/10.1007/s10880-016-9461-z

1. Robinson, A., Roberts, J., Brady, N., McQuillin, S., Warren, S. (2016). Physiological Correlates of Maternal Responsivity in Mothers of Preschoolers with Fragile X Syndrome. *American Journal on Intellectual and Developmental Disabilities. 121(2), 111-120.*

1. McQuillin, S., Strait, G., Saeki, E. (2015). Program support and value of training in mentor satisfaction and anticipated continuation of school-based mentoring relationships. *Mentoring and Tutoring: Partnership in Learning, 23(2), 133-148.*

1. Terry, J., Smith, A., Warren, P., Miller, M., McQuillin, S., Wolfer, T., & Weist, M. (2015). Incorporation of evidence-based practices into faith-based organization service programs. *Journal of Psychology and Theology, 43, 212-223.*

1. McQuillin, S., Smith, B., & Strait, G., Ingram, A., (2015). Brief Instrumental School- Based Mentoring for First and Second Year Middle School Students: A Randomized Evaluation. *Journal of Community Psychology 43(7), 885-889.*

1. Strait, G., McQuillin, S., Terry, J., Smith, B. (2014). School-based motivational interviewing with students,teachers, and parents: new developments and future direction. *Advances in School Mental Health Promotion, 7(4), 2014, 205-207.*

1. Terry, J. D., Smith, B. H., & McQuillin, S. D. (2014). Teaching evidence-based practice in service-learning: A model for education and service. *Journal on Excellence in College Teaching, 25(1), 55-69.*

1. Roberts, J., Tonnsen, B., Robinson, M., McQuillin, S., Hatton, D. (2014) Temperament factor structure in fragile x syndrome: The children's behavior questionnaire. *Research in Developmental Disabilities, 35, 563-571.*

1. Terry, J., Strait, G., McQuillin, S., Smith, B. (2014). Dosage effects of motivational interviewing onmiddle-school students' academic performance: Randomized evaluation of one versus two sessions. *Advances in School Mental Health Promotion, 7(1), 62-74.*

1. McQuillin, S., Terry, J., Strait, S., Smith, B. (2013). Innovation in school-based mentoring: matching the context, structure, and goals of mentoring with evidence-based practices. *Advances in School Mental Health Promotion, 6(4), 280-294.*

1. Terry, J., Strait, G., Smith, B., McQuillin, S., ( 2013). Motivational Interviewing to Improve Middle School Students' Academic performance: a replication study. *Journal of Community Psychology.*

1. Strait, G., McQuillin, S., Smith, B. (2012). Randomized trial of motivational interviewing toimprove students' academic performance. *Journal of Community Psychology, 40(8), 1032-1039.*

1. Strait, G. McQuillin, S., Smith, B., Englund, J. (2012). Using motivational interviewing with children andadolescents: a cognitive and neuro developmental perspective. *Advances in School Mental Health Promotion, 5(4), 1-15.*

1. Kelly, R., Hills, K., Huebner, S., McQuillin, S. (2012). The longitudinal stability and dynamics of group membership in the dual-factor model of mental health: psychosocial predictors of mental health. *Canadian Journal of School Psychology, 27(4), 337-355.*

1. McQuillin, S., Smith, B., & Strait, G. (2011). Randomized evaluation of a single semester transitional mentoringprogram for first year middle school students: A cautionary result for brief school-based mentoring programs. *Journal of Community Psychology, 39(7), 844-859.*

1. Warren, P., Richardson, D., & McQuillin, S. (2011). Distinguishing forms of nondirect aggression. *Aggressive Behavior, 37, 291-301.*

1. Smith, B., Gahagan, J., McQuillin, S., Haywood, B., Cole, P., Bolton, C., & Wampler, M.(2011). The development of a service-learning program for first-year students based on the hallmarks of high quality service-learning and rigorous program evaluation. *Innovative Higher Education, 36,1-17.*

1. Fairchild, A., & McQuillin S., (2010). Evaluating mediation and moderation effects in school psychology: Apresentation of methods and review of current practice. *Journal of School Psychology,45, 54-84.*

## Other Publications

McQuillin, S., Smith, B., McLelland, B. (2014) Using practice-based evidence to inform the development of school-based mentoring. *The Community Psychologist, 47, 2, 31-32.*

Strait, G., Terry, J., McQuillin, S., Smith, B. (2013). Motivational interviewing: ready for adults and emergent for adolescents. *The Community Psychologist, 46(1), 26-28.* 

Smith, B., McQuillin, S., & Shapiro, C. (2008). An installation adaptation diffusion model of university-community-school partnerships. *The Community Psychologist, 42(1),43-46.*

#Presentations

McQuillin, S., Lyons, M. (2017) Treatment construct validity in school-based mentoring intervention research. Paper presented at the annual meeting for the Society for Research on Educational Effectiveness, Washington, DC. 

McQuillin, S., McDaniel, H. (2017) Using Motivational Interviewing in School-Based Mentoring Programs. Paper presented at the annual meeting for the Society for Prevention Research, Washington, DC. 

Lyons, M., McQuillin, S., Lamont, A. (2017) A Reanalysis of the Student Mentoring Program: Estimating Treatment Effects by the Quality of the Mentoring Relationship. 

McQuillin, S. (2017) Changing the way we train mentors: Just in Time Training & Motivational Interviewing. Paper presented at the annual National Mentoring Summit in Washington, DC. 

McQuillin, S., Jacobs, G., Sajovek, P., Johnson, B., Anderson, A. (2016). Brief Instrumental School-Based Mentoring for Adolescents-Theory, Practice, and Impact Evaluations. Symposium presented at the annual meeting for the American Psychological Association, Denver, CO. 

McQuillin, S. (2015). From harmful to helpful: transforming youth mentoring through task shifting, evidence- based practice, and practice-based evidence. Symposium presented at the annual meeting for the Association of Psychological Science, New York, NY. 

McQuillin, S. (2014). The University of Houston Academic Mentoring Program for Education and Development (AMPED). Paper presented at the annual meeting of the American Psychological Association, Washington, DC.

McQuillin, S., Smith, B., McLelland, B. (2014). Motivaitonal Interviewing and School-Based Mentoring: Process, Procedures, Implementation, and Results. Paper presented at the annual meeting of the American Psychological Association, Washington, DC. 

McQuillin, S. (2014). School-based instrumental mentoring for middle-school students: past, present future. Poster presented at the annual meeting of the Society for Prevention Research, Washington, DC. 

McQuillin, S., Saeki, E. (2013). Mechanisms of Change in School-Based Psychosocial Interventions. Paper presented at the annual meeting of the National Association of School Psychologists, Seattle, WA. 

McQuillin, S., Cavell, T., Elledge, E., Strait, G., Smith, B., Terry, J. (2012). Brief manualized school-based mentoring interventions for secondary students: Results and suggestions from two randomized trials. In McQuillin, S. (Chair), Principles of change in school-based mentoring and coaching interventions. New findingsand implications from five randomized controlled studies. Presented at the symposium conducted at the 46th annual convention of the Association for Behavioral and Cognitive Therapies, National Harbor, MD. 

Smith, B., Sanders, M., McQuillin, S., Fairchild, A., & Anello, V. (2010). Investing in the future of psychotherapy research: Statistical best practices and seven methodological considerations for studying mechanisms of action. Symposium presented at the annual meeting of the Association for Cognitive and Behavioral Therapies, San Francisco, CA. 

McQuillin, S. (2010). Randomized evaluation of a school based mentoring program for transitioning middle school students: An efficacy trial. Poster presented at the annual meeting of the Association for Cognitive and Behavioral Therapies, San Francisco, CA. 

McQuillin, S. & Annelo, V. (2010). Applications of the public health model to school based mental health collaboration in school-university-community partnerships. Paper presented at the annual meeting of the National Association of School Psychologists in Chicago, IL.

McQuillin, S. (2010). Statistical mediation and moderation in program design and evaluation. Paper presented at the annual meeting of the National Association of School Psychologists in Chicago, IL.

Strait, G., Cole, C., McQuillin, S. (2009, February). Psychometric properties of brief basic math skill assessments.Paper presented at the annual meeting of the National Association of School Psychologist in Boston, MA.

Pender, C.A.S., Strait, G., McQuillin, S., Carl, W. (2008, February). Efficacy and psychometrics of a middle-school remedial math curriculum. Oral presentation presented at the annual meeting of the National Association of School Psychologists in New Orleans, LA.

Pender, C.A.S., Smith, B., Strait, G., McQuillin, S., Ardoin, S., (2007, November). Math intervention delivered by paraprofessionals to high-risk middle-school students in the challenging horizons program. Poster presented at the annual meeting of the Association for Behavioral and Cognitive Therapies in Philadelphia, PA.

Pender, C.A.S., Strait, G., & McQuillin, S. (2007, March). Improving middle school students' math word problem solving skills. Poster presented at the annual meeting of the National Association of School Psychologists in New York, NY.

McQuillin, S., & Terry, J. (2007, April). The challenging horizons program: Contributions of USC undergraduates to the development of an evidence-based, award winning program. Paper presented at the annual Discovery Day of the University of South Carolina, Columbia, SC.

McQuillin, S., Thompson, S. & Strait, G., Smith, B. & Pender, C. (2006, April). Curriculum based measurement and state-of-the-art training to help middle school students solve math word problems. Paper presented at the annual Discovery Day of the University of South Carolina, Columbia, SC.

Strait, G., McQuillin, S., Thompson, S. Smith, B. & Pender, C.(2006, April). State-of-the-Art Individually Paced Intervention to Improve Math Word Problem Solving. Poster presented at the annual Discover Day of the University of South Carolina, Columbia, SC.

##Invited talks and Workshops
Deustch, N., McQuillin, S. (2016). Getting Results for Our Youth: Evaluating Programs for Continuous Improvement. Webinar presented on behalf of the My Brothers Keeper Alliance Webinar Series, via MENTOR, the National Mentoring Partnership.

Garringer, M., McQuillin, S. (2016). Introduction to Program Evaluation for Youth Mentoring Programs. Workshop presented at MENTOR-Con. Pittsburgh, PA.

McQuillin, S. (2015). Improving the impact of school-based mentoring. Keynote speaking, Texas Mentoring Summit, San Antonio, TX.

McQuillin, S. (2014). Using motivational interviewing in the context of teacher coaching. Three day workshop presented to Houston area master coaches. Teach2Lead Houston, Houston, TX.

McQuillin, S., McLelland, B.(2013). Motivational Interviewing in Schools. Workshop provided to pre-doctoral interns as part of their APA Accredited Internship in Psychology. Cypress, TX

McQuillin, S., McLelland, B.(2012). Motivating students to succeed in school. Workshop provided to student support counselors at YES Prep Charter School, Houston, TX.

McQuillin, S., McLelland, B.(2012). Mentoring and Motivational Interviewing. Workshop provided to pre-doctoral interns as part of their APA Accredited Internship in Psychology. Cypress, TX

#Awards

3rd Place in Social Psychological Sciences, Discovery Day, University of South Carolina \hfill 2006

Megellan Voyager Research Award \hfill 2007

2nd Place in Social Psychological Sciences, Discovery Day, University of South Carolina \hfill 2007

Inducted into Phi Beta Kappa National Honor Society \hfill 2007

USC Graduate Student Travel Grants, totaling $1,700 \hfill 2010

American Psychological Association Achievement Award for Early Career Professionals \hfill 2014

University of Houston Certificate of Excellence on Behalf of Provost Short \hfill 2015

Award for Research Excellence, University of Houston \hfill 2015

Society for the Study of School Psychology Early Career Award \hfill 2016

#Teaching

##Graduate

Evidence-Based Interventions in Psychology, University of Houston

History and Philosophy of Psychological Systems, University of Houston

Research Methods in School Psychology, University of Houston

Ecological Behavioral Interventions, University of Houston

Behavioral Consultation, University of Houston

Systems Applications in Psychological Services, University of South Carolina

Assessment of Emotional and Behavioral Functioning, University of South Carolina

Psychological Consultation and Systems Interventions, University of South Carolina

Lab Instructor: Quantiative Methods for Behavioral Data I, University of South Carolina

Lab Instructor: Quantiatative Methods for Behavioral Data II, University of South Carolina

##Undergraduate 

Research Methods in Psychology, University of South Carolina

Research Methods in Human Development, University of Houston

Children & Exceptionality, University of South Carolina
